// <auto-generated />
using System;
using HardwareTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HardwareTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915062512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HardwareTracker.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedEmployeeId = 1,
                            Category = "Laptop",
                            Model = "Dell Latitude 5540",
                            SerialNumber = "LT-2024-001",
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 2,
                            AssignedEmployeeId = 2,
                            Category = "Laptop",
                            Model = "MacBook Pro 16",
                            SerialNumber = "LT-2024-002",
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Monitor",
                            Model = "Dell UltraSharp U2723QE",
                            SerialNumber = "MN-2024-101",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Monitor",
                            Model = "LG 27UK850",
                            SerialNumber = "MN-2024-102",
                            Status = "InService"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Peripheral",
                            Model = "Logitech MX Keys",
                            SerialNumber = "KB-2023-550",
                            Status = "Disposed"
                        });
                });

            modelBuilder.Entity("HardwareTracker.Models.AssignmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    // Composite index supports efficient chronological queries per hardware unit.
                    b.HasIndex("AssetId", "AssignedDate");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AssignmentHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            AssignedDate = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            EmployeeName = "Anna Kowalska",
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            AssignedDate = new DateTime(2024, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            EmployeeName = "Marek Nowak",
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 3,
                            AssignedDate = new DateTime(2023, 6, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            EmployeeName = "Zofia Wisniewska",
                            ReturnedDate = new DateTime(2023, 12, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 4,
                            AssetId = 4,
                            AssignedDate = new DateTime(2024, 3, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeName = "Service",
                            Status = "InService"
                        },
                        new
                        {
                            Id = 5,
                            AssetId = 5,
                            AssignedDate = new DateTime(2024, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeName = "Disposed",
                            ReturnedDate = new DateTime(2024, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Disposed"
                        });
                });

            modelBuilder.Entity("HardwareTracker.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Email = "anna.kowalska@company.com",
                            FirstName = "Anna",
                            HireDate = new DateTime(2023, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kowalska"
                        },
                        new
                        {
                            Id = 2,
                            Department = "DevOps",
                            Email = "marek.nowak@company.com",
                            FirstName = "Marek",
                            HireDate = new DateTime(2023, 3, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            Department = "HR",
                            Email = "zofia.wisniewska@company.com",
                            FirstName = "Zofia",
                            HireDate = new DateTime(2022, 11, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Wisniewska"
                        });
                });

            modelBuilder.Entity("HardwareTracker.Models.Asset", b =>
                {
                    b.HasOne("HardwareTracker.Models.Employee", "AssignedEmployee")
                        .WithMany("AssignedAssets")
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedEmployee");
                });

            modelBuilder.Entity("HardwareTracker.Models.AssignmentHistory", b =>
                {
                    b.HasOne("HardwareTracker.Models.Asset", "Asset")
                        .WithMany("AssignmentHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardwareTracker.Models.Employee", "Employee")
                        .WithMany("AssignmentHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HardwareTracker.Models.Asset", b =>
                {
                    b.Navigation("AssignmentHistories");
                });

            modelBuilder.Entity("HardwareTracker.Models.Employee", b =>
                {
                    b.Navigation("AssignedAssets");

                    b.Navigation("AssignmentHistories");
                });
#pragma warning restore 612, 618
        }
    }
}